baseurl = "https://traefik.io/"
languageCode = "en-us"
title = "Træfɪk"

[params]
  # description = "A modern reverse proxy"
  author = "Emile Vauge"
  github = "containous"
  twitter = "traefikproxy"
  logo = "/traefik.logo.png"
  mainIcon = "/traefik.logo.svg"
  cover = "/cover.planes.jpg"
